### ISSUE TITLE
Template installation failed: Command failed

### ISSUE THREAD

**Issue by ajamous** [strapi/strapi-template-corporate#13]
Both npx and yarn commands end up with the same issue below

```shell

Creating a new Strapi application at /Users/aj/programming/tcxc-strapi.
Creating files.
Error: ⛔️ Template installation failed: Command failed: /bin/sh -c npm view https://github.com/strapi/strapi-template-corporate name version --silent


    at createProject (/Users/aj/.config/yarn/global/node_modules/@strapi/generate-new/lib/create-project.js:82:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-strapi-app
Arguments: tcxc-strapi --template https://github.com/strapi/strapi-template-corporate
Directory: /Users/aj/programming
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

```

**Comment by jsanta** [comment]
Same here:
```
npx create-strapi-app project-front --template https://github.com/strapi/strapi-template-corporate

npx: installed 104 in 28.977s
? Choose your installation type Quickstart (recommended)
Creating a quickstart project.
Creating a new Strapi application at /private/tmp/project-front.
Creating files.
Error: ⛔️ Template installation failed: Command failed: /bin/sh -c npm view https://github.com/strapi/strapi-template-corporate name version --silent


    at createProject (/Users/JSanta/.npm/_npx/7176/lib/node_modules/create-strapi-app/node_modules/@strapi/generate-new/lib/create-project.js:82:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async createQuickStartProject (/Users/JSanta/.npm/_npx/7176/lib/node_modules/create-strapi-app/node_modules/@strapi/generate-new/lib/create-quickstart-project.js:23:3)
```
Just in case I also tried changing my project's name  so it doesn't have any - between. Same error.

By the way this is using current strapi v4 (I was willing to see in action all new functionalities, but I guess  we'll have to stay in v3 for a while).

**Comment by panilo** [comment]
Same issue here, 

WIN 10 
Git bash 
npm/npx version 6.14.15

```npx create-strapi-app my-app-name --template https://github.com/strapi/strapi-template-corporate
npx: installed 104 in 8.929s
? Choose your installation type Quickstart (recommended)
Creating a quickstart project.
Creating a new Strapi application at C:\Users\deso9\Desktop\gatsby_corporate_starter\my-app-name.
Creating files.
Error: ⛔️ Template installation failed: Command failed: C:\WINDOWS\system32\cmd.exe /q /s /c "npm view https://github.com/strapi/strapi-template-corporate name version --silent"


    at createProject (C:\Users\deso9\AppData\Roaming\npm-cache\_npx\23916\node_modules\create-strapi-app\node_modules\@strapi\generate-new\lib\create-project.js:82:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async createQuickStartProject (C:\Users\deso9\AppData\Roaming\npm-cache\_npx\23916\node_modules\create-strapi-app\node_modules\@strapi\generate-new\lib\create-quickstart-project.js:23:3)```

**Comment by lyndseysc** [comment]
was facing this issue too and found a solution,

templates and starters that are compatible with v4 appear to have been migrated to https://github.com/strapi/starters-and-templates

The commands in the readme of this repo won't work anymore when running v4, as they point to this repo. 

`yarn create strapi-app my-app-template --template corporate` does work
